name: Minions-Miner
main: com.thecrappiest.minions.miner.MinerCore
version: 0.1.3
api-version: 1.13
depend: [Minions-Revamped]

# Update 0.1.3 for Minions-Miner 

# Updated Minions-Revamped dependency. (Minions-Revamped 0.3.1)
# Recoded portions to match other minions and API methods.
# Fixed experience not being subtracted correctly when miner bottles it.
# Optimized bottling experience.