name: Minions-Miner
main: com.thecrappiest.minions.miner.MinerCore
version: 0.1.2
api-version: 1.13
depend: [Minions-Revamped]

# Update 0.1.2 for Minions-Miner 

# Updated Minions-Revamped dependency. (Minions-Revamped 0.2.5)
# Added radius usage. (Will mine the amount of "radius" infront of the minion)
# Cleaned up some miscellaneous code in PerformMinerTask
