name: Minions-Miner
main: com.thecrappiest.minions.miner.MinerCore
version: 0.1.1
api-version: 1.13
depend: [Minions-Revamped]

# Update 0.1.1 for Minions-Miner 

# Updated Minions-Revamped dependency. (Minions-Revamped 0.1.5)
# Fixed sections where miner was called "collector".
# Minion Type NBT tag will get type from config.
