name: Minions-Miner
main: com.thecrappiest.minions.miner.MinerCore
version: 0.1.0
api-version: 1.13
depend: [Minions-Revamped]

# Update 0.1.0 for Minions-Miner 

# Updated Minions-Revamped dependency. (Minions-Revamped 0.1.4)
# Cleaned up code.
